---
name: "linting - all"
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  lint:
    name: "linting (python)"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Set up Python"
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"
      - name: "install linting tooling"
        continue-on-error: true
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt ; pylint **/*.py
      - name: "run linting via tox"
        run: |
          tox -e linting
